# -*- coding: utf-8 -*-
"""sleep_stage_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wp9XHX-IWvW-iZ1_3f1vAA14axy-hZ2C

# 😴 Sleep Stage Classification
**Super AI Engineer Season 6 — Signal Processing Hackathon**

**Approach:** Feature Engineering + LightGBM  
**Metric:** F1-Score (weighted)  
**Classes:** W, N1, N2, N3, R

## 📦 Cell 1: Install & Import
"""

# Install dependencies (run once)
!pip install lightgbm openpyxl -q

import pandas as pd
import numpy as np
from scipy import stats, signal
from scipy.fft import fft, fftfreq
from scipy.ndimage import median_filter
import lightgbm as lgb
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score, classification_report
import os, glob, warnings
warnings.filterwarnings('ignore')

print('✅ All imports successful')

"""## ⚙️ Cell 2: Configuration"""

# ===== CONFIG — แก้ path ตาม Google Drive =====
from google.colab import drive
drive.mount('/content/drive')

BASE_DIR = '/content/drive/MyDrive/Colab/ss6_mh4.3'

TRAIN_DIR   = f'{BASE_DIR}/train/train'
TEST_DIR    = f'{BASE_DIR}/test_segment/test_segment'
SAMPLE_SUB  = f'{BASE_DIR}/sample_submission.csv'
OUTPUT_PATH = f'{BASE_DIR}/submission.csv'

# Signal parameters
FS       = 16          # sampling rate (Hz)
SEG_SEC  = 30          # segment length (seconds)
SEG_LEN  = FS * SEG_SEC  # = 480 data points per segment

LABEL_COL = 'Sleep_Stage'

print(f'Segment length: {SEG_LEN} rows (= {SEG_SEC}s × {FS}Hz)')
print(f'Train dir: {TRAIN_DIR}')
print(f'Test dir:  {TEST_DIR}')

"""## 🔧 Cell 3: Feature Extraction Functions"""

def safe_array(series):
    """แปลง Series → numpy array โดย drop NaN และป้องกัน empty array"""
    arr = series.values.astype(float)
    arr = arr[~np.isnan(arr)]
    return arr if len(arr) > 0 else np.zeros(1)


def band_power(fft_vals, freqs, f_low, f_high):
    """คำนวณ power ใน frequency band"""
    mask = (freqs >= f_low) & (freqs < f_high)
    return np.sum(fft_vals[mask] ** 2)


def extract_features(seg, seg_idx=0, total_segs=1):
    """
    Extract feature vector จาก 1 segment (480 rows = 30 วินาที)
    Returns: dict of features
    """
    features = {}

    # ──────────────────────────────────────────────
    # 1. Statistical Features (ทุก channel)
    # ──────────────────────────────────────────────
    channels = ['BVP', 'ACC_X', 'ACC_Y', 'ACC_Z', 'TEMP', 'EDA', 'HR', 'IBI']
    for col in channels:
        if col not in seg.columns:
            continue
        x = safe_array(seg[col])
        features[f'{col}_mean']   = np.mean(x)
        features[f'{col}_std']    = np.std(x)
        features[f'{col}_min']    = np.min(x)
        features[f'{col}_max']    = np.max(x)
        features[f'{col}_median'] = np.median(x)
        features[f'{col}_q25']    = np.percentile(x, 25)
        features[f'{col}_q75']    = np.percentile(x, 75)
        features[f'{col}_iqr']    = np.percentile(x, 75) - np.percentile(x, 25)
        features[f'{col}_skew']   = stats.skew(x)
        features[f'{col}_kurt']   = stats.kurtosis(x)
        features[f'{col}_rms']    = np.sqrt(np.mean(x ** 2))
        features[f'{col}_range']  = np.max(x) - np.min(x)

    # ──────────────────────────────────────────────
    # 2. BVP Frequency Domain (FFT)
    # ──────────────────────────────────────────────
    bvp = np.nan_to_num(seg['BVP'].values.astype(float)) if 'BVP' in seg.columns else np.zeros(SEG_LEN)
    fft_vals = np.abs(fft(bvp))[:len(bvp) // 2]
    freqs    = fftfreq(len(bvp), d=1 / FS)[:len(bvp) // 2]

    vlf   = band_power(fft_vals, freqs, 0.003, 0.04)
    lf    = band_power(fft_vals, freqs, 0.04,  0.15)
    hf    = band_power(fft_vals, freqs, 0.15,  0.40)
    total = vlf + lf + hf + 1e-10

    features['bvp_vlf']     = vlf
    features['bvp_lf']      = lf
    features['bvp_hf']      = hf
    features['bvp_lf_hf']   = lf / (hf + 1e-10)   # สำคัญสำหรับ REM detection
    features['bvp_lf_norm'] = lf / total
    features['bvp_hf_norm'] = hf / total

    # ──────────────────────────────────────────────
    # 3. HRV Features (จาก IBI)
    # ──────────────────────────────────────────────
    if 'IBI' in seg.columns:
        ibi = safe_array(seg['IBI'])
        ibi = ibi[ibi > 0]   # กรอง 0 ออก
        if len(ibi) > 1:
            diff_ibi = np.diff(ibi)
            features['hrv_sdnn']     = np.std(ibi)
            features['hrv_rmssd']    = np.sqrt(np.mean(diff_ibi ** 2))
            features['hrv_pnn50']    = np.mean(np.abs(diff_ibi) > 50)
            features['hrv_mean_ibi'] = np.mean(ibi)
            features['hrv_cv']       = np.std(ibi) / (np.mean(ibi) + 1e-10)
        else:
            for k in ['hrv_sdnn', 'hrv_rmssd', 'hrv_pnn50', 'hrv_mean_ibi', 'hrv_cv']:
                features[k] = 0.0

    # ──────────────────────────────────────────────
    # 4. ACC Magnitude & Motion Features
    # ──────────────────────────────────────────────
    if all(c in seg.columns for c in ['ACC_X', 'ACC_Y', 'ACC_Z']):
        ax = np.nan_to_num(seg['ACC_X'].values.astype(float))
        ay = np.nan_to_num(seg['ACC_Y'].values.astype(float))
        az = np.nan_to_num(seg['ACC_Z'].values.astype(float))
        mag = np.sqrt(ax**2 + ay**2 + az**2)

        features['acc_mag_mean'] = np.mean(mag)
        features['acc_mag_std']  = np.std(mag)
        features['acc_mag_max']  = np.max(mag)
        features['acc_sma']      = np.mean(np.abs(ax) + np.abs(ay) + np.abs(az))

        # Zero-crossing rate (proxy for movement)
        for name, arr in [('ACC_X', ax), ('ACC_Y', ay), ('ACC_Z', az)]:
            centered = arr - np.mean(arr)
            zcr = np.sum(np.diff(np.sign(centered)) != 0) / len(centered)
            features[f'{name}_zcr'] = zcr

    # ──────────────────────────────────────────────
    # 5. EDA — slope & peak count
    # ──────────────────────────────────────────────
    if 'EDA' in seg.columns:
        eda = np.nan_to_num(seg['EDA'].values.astype(float))
        t = np.arange(len(eda))
        slope, intercept = np.polyfit(t, eda, 1) if np.std(eda) > 0 else (0, 0)
        features['eda_slope'] = slope
        # peak count (SCR)
        peaks, _ = signal.find_peaks(eda, height=np.mean(eda))
        features['eda_peak_count'] = len(peaks)

    # ──────────────────────────────────────────────
    # 6. TEMP — slope (body temp ลดลงเมื่อเข้า N3)
    # ──────────────────────────────────────────────
    if 'TEMP' in seg.columns:
        temp = np.nan_to_num(seg['TEMP'].values.astype(float))
        t = np.arange(len(temp))
        slope, _ = np.polyfit(t, temp, 1) if np.std(temp) > 0 else (0, 0)
        features['temp_slope'] = slope

    # ──────────────────────────────────────────────
    # 7. Contextual / Temporal Features
    # ──────────────────────────────────────────────
    features['segment_idx']      = seg_idx
    features['segment_idx_norm'] = seg_idx / max(total_segs - 1, 1)
    features['total_segments']   = total_segs

    return features


print('✅ Feature extraction functions defined')

# ตรวจสอบ structure และ format ของไฟล์
import os, glob

# ดู train folder
train_files = sorted(
    glob.glob(f'{TRAIN_DIR}/**/*', recursive=True)
)
print("Train files (first 20):")
for f in train_files[:20]:
    print(f)

print(f"\nTotal files: {len(train_files)}")

"""## 📂 Cell 4: Load Training Data"""

import pandas as pd
import numpy as np
import glob, os
from tqdm.notebook import tqdm  # progress bar

train_features = []
train_labels   = []

subject_files = sorted(glob.glob(os.path.join(TRAIN_DIR, '*.csv')))
print(f'📁 Found {len(subject_files)} train subjects')

for fpath in tqdm(subject_files, desc='Loading subjects'):
    df = pd.read_csv(fpath)

    n_segs = len(df) // SEG_LEN

    for i in range(n_segs):
        seg = df.iloc[i * SEG_LEN:(i + 1) * SEG_LEN]

        # Label
        if LABEL_COL not in seg.columns:
            continue
        label = seg[LABEL_COL].mode()[0]

        feat = extract_features(seg, seg_idx=i, total_segs=n_segs)
        train_features.append(feat)
        train_labels.append(label)

X_train = pd.DataFrame(train_features).fillna(0)
y_raw   = np.array(train_labels)

le = LabelEncoder()
y_train = le.fit_transform(y_raw)

print(f'\n✅ Train set: {X_train.shape[0]} segments × {X_train.shape[1]} features')
print(f'   Classes: {list(le.classes_)}')
print('\n📊 Label distribution:')
print(pd.Series(y_raw).value_counts())

"""## 📊 Cell 5: EDA — Class Distribution"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

# Label distribution
counts = pd.Series(y_raw).value_counts().sort_index()
axes[0].bar(counts.index, counts.values, color=['#4C72B0', '#DD8452', '#55A868', '#C44E52', '#8172B3'])
axes[0].set_title('Sleep Stage Distribution (Train)', fontsize=13)
axes[0].set_xlabel('Sleep Stage')
axes[0].set_ylabel('Count')
for i, (k, v) in enumerate(counts.items()):
    axes[0].text(i, v + 50, f'{v}\n({v/len(y_raw)*100:.1f}%)', ha='center', fontsize=9)

# Feature correlation heatmap (top features)
top_cols = ['BVP_mean', 'HR_mean', 'EDA_mean', 'TEMP_mean',
            'acc_mag_mean', 'hrv_sdnn', 'hrv_rmssd', 'bvp_lf_hf']
available = [c for c in top_cols if c in X_train.columns]
corr = X_train[available].corr()
im = axes[1].imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
axes[1].set_xticks(range(len(available)))
axes[1].set_yticks(range(len(available)))
axes[1].set_xticklabels(available, rotation=45, ha='right', fontsize=8)
axes[1].set_yticklabels(available, fontsize=8)
axes[1].set_title('Feature Correlation (Key Features)', fontsize=13)
plt.colorbar(im, ax=axes[1])

plt.tight_layout()
plt.savefig('eda.png', dpi=100, bbox_inches='tight')
plt.show()
print('✅ EDA complete')

"""## 🤖 Cell 6: Train LightGBM"""

params = {
    'objective':         'multiclass',
    'num_class':         len(le.classes_),
    'metric':            'multi_logloss',
    'learning_rate':     0.05,
    'num_leaves':        127,
    'max_depth':         -1,
    'min_child_samples': 20,
    'feature_fraction':  0.8,
    'bagging_fraction':  0.8,
    'bagging_freq':      5,
    'lambda_l1':         0.1,
    'lambda_l2':         0.1,
    'is_unbalance':      True,   # ← จัดการ class imbalance
    'verbose':          -1,
    'n_jobs':           -1,
    'seed':              42,
}

dtrain = lgb.Dataset(X_train, label=y_train)

print('🔍 Running 5-Fold CV to find best rounds...')
cv_result = lgb.cv(
    params,
    dtrain,
    num_boost_round=1000,
    nfold=5,
    stratified=True,
    callbacks=[
        lgb.early_stopping(stopping_rounds=50, verbose=False),
        lgb.log_evaluation(period=100)
    ]
)

best_rounds = len(cv_result['valid multi_logloss-mean'])
print(f'\n✅ Best rounds: {best_rounds}')
print(f'   Best CV loss: {min(cv_result["valid multi_logloss-mean"]):.4f}')

print('🚀 Training final model...')
model = lgb.train(
    params,
    dtrain,
    num_boost_round=best_rounds,
    callbacks=[lgb.log_evaluation(period=100)]
)

# Train set performance check
y_pred_train = model.predict(X_train).argmax(axis=1)
f1_train = f1_score(y_train, y_pred_train, average='weighted')
print(f'\n📈 Train F1 (weighted): {f1_train:.4f}')
print('\n📋 Classification Report (Train):')
print(classification_report(y_train, y_pred_train, target_names=le.classes_))

"""## 📊 Cell 7: Feature Importance"""

importance_df = pd.DataFrame({
    'feature':    X_train.columns,
    'importance': model.feature_importance(importance_type='gain')
}).sort_values('importance', ascending=False)

top_n = 25
fig, ax = plt.subplots(figsize=(10, 8))
top = importance_df.head(top_n)
bars = ax.barh(top['feature'][::-1], top['importance'][::-1], color='steelblue')
ax.set_title(f'Top {top_n} Feature Importance (Gain)', fontsize=14)
ax.set_xlabel('Importance (Gain)')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=100, bbox_inches='tight')
plt.show()

print('\nTop 10 features:')
print(importance_df.head(10).to_string(index=False))

"""## 🔮 Cell 8: Predict Test Set"""

def predict_subject(subject_path, model, feature_cols, le, smooth=True):
    """
    โหลด segment files ของ 1 subject แล้ว predict
    Returns: dict {segment_id: predicted_label}
    """
    seg_files = sorted(
        glob.glob(os.path.join(subject_path, '*.xlsx')) +
        glob.glob(os.path.join(subject_path, '*.csv'))
    )
    if not seg_files:
        return {}

    seg_features = []
    seg_ids      = []

    for i, sf in enumerate(seg_files):
        try:
            seg_df = pd.read_excel(sf) if sf.endswith('.xlsx') else pd.read_csv(sf)
        except:
            continue
        feat = extract_features(seg_df, seg_idx=i, total_segs=len(seg_files))
        seg_features.append(feat)
        seg_id = os.path.splitext(os.path.basename(sf))[0]
        seg_ids.append(seg_id)

    if not seg_features:
        return {}

    X_test_s = pd.DataFrame(seg_features).reindex(columns=feature_cols, fill_value=0)
    preds_int = model.predict(X_test_s).argmax(axis=1)

    if smooth and len(preds_int) > 3:
        # Temporal smoothing ด้วย median filter (window=3)
        preds_int = median_filter(preds_int, size=3)

    pred_labels = le.inverse_transform(preds_int)
    return dict(zip(seg_ids, pred_labels))


# ──────────────────────────────────────────────────────
# Predict all test subjects
# ──────────────────────────────────────────────────────
test_results = {}
feature_cols = list(X_train.columns)

subject_folders = sorted(os.listdir(TEST_DIR)) if os.path.exists(TEST_DIR) else []
print(f'📁 Found {len(subject_folders)} test subjects')

for subj in subject_folders:
    subj_path = os.path.join(TEST_DIR, subj)
    if not os.path.isdir(subj_path):
        continue
    result = predict_subject(subj_path, model, feature_cols, le, smooth=True)
    test_results.update(result)
    print(f'  ✅ {subj}: {len(result)} segments predicted')

print(f'\nTotal predictions: {len(test_results)}')

"""## 📤 Cell 9: Create Submission"""

sample_sub = pd.read_csv(SAMPLE_SUB)
print(f'Sample submission shape: {sample_sub.shape}')
print(sample_sub.head())

sub = sample_sub.copy()
sub['labels'] = sub['id'].map(test_results)

# ตรวจสอบ missing predictions
missing = sub['labels'].isna().sum()
if missing > 0:
    print(f'⚠️  {missing} missing predictions — filling with most common class (W)')
    sub['labels'] = sub['labels'].fillna('W')  # fallback

sub.to_csv(OUTPUT_PATH, index=False)

print(f'\n✅ Submission saved: {OUTPUT_PATH}')
print(f'   Total rows: {len(sub)}')
print('\n📊 Prediction distribution:')
print(sub['labels'].value_counts())
print('\n📋 Preview:')
sub.head(10)

"""## ✅ Cell 10: Quick Sanity Check"""

print('=== SUBMISSION SANITY CHECK ===')
print(f'Rows:          {len(sub)}')
print(f'Missing:       {sub["labels"].isna().sum()}')
print(f'Valid classes: {set(sub["labels"].unique()) <= set(le.classes_)}')
print(f'Classes used:  {sorted(sub["labels"].unique())}')

fig, ax = plt.subplots(figsize=(7, 4))
pred_counts = sub['labels'].value_counts().sort_index()
ax.bar(pred_counts.index, pred_counts.values, color='steelblue', edgecolor='white')
ax.set_title('Submission — Predicted Label Distribution', fontsize=13)
ax.set_xlabel('Sleep Stage')
ax.set_ylabel('Count')
for i, (k, v) in enumerate(pred_counts.items()):
    ax.text(i, v + 5, str(v), ha='center', fontsize=10)
plt.tight_layout()
plt.show()

print('\n🎉 All done! Ready to submit.')

"""---
## 💡 Tips สำหรับการปรับปรุง Score

### ลอง ถ้า score ยังไม่ถึง baseline
1. **เพิ่ม `class_weight`** — ปรับ weight ของ N1 (น้อยที่สุด) ให้หนักขึ้น
2. **ปรับ smoothing window** — ลอง `size=5` แทน `size=3`
3. **เพิ่ม lag features** — เอา feature ของ segment ก่อนหน้า/ถัดไปมา concatenate
4. **Normalize per-subject** — StandardScaler แยก fit ต่อ subject

### ลอง ถ้า score ดีแล้วอยากขึ้นอีก
1. **XGBoost + LightGBM ensemble** — average probabilities แล้ว argmax
2. **Viterbi decoding** — ใช้ transition matrix ของ sleep stages เป็น HMM
3. **Subject-specific threshold** — ปรับ probability threshold ต่อ subject

```python
# Ensemble example
prob_lgb = lgb_model.predict(X)
prob_xgb = xgb_model.predict_proba(X)
prob_ensemble = (prob_lgb + prob_xgb) / 2
preds = prob_ensemble.argmax(axis=1)
```
"""